apiVersion: apps/v1
kind: Deployment
metadata:
   name: deployment-demo
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         deployment: web
   template:
      metadata:
         labels:
            deployment: web
      spec:
         containers:
            - name: deployment-site
              image: chaymariahi/jenkins-docker-hub
              imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
   name: deployment-entrypoint
   namespace: default
spec:
   type: NodePort
   selector:
      deployment: web
   ports:
      - port: 8081
        targetPort: 8081
        nodePort: 32000