apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: frontend
    service: webapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    service: deployment